-- Create Projects Table
create table if not exists projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  status text default 'Active', -- Active, Archived, On Hold
  start_date date,
  end_date date,
  manager_id uuid references auth.users,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table projects enable row level security;

-- Policies
create policy "Projects are viewable by everyone." on projects for select using (true);
create policy "Authenticated users can insert projects." on projects for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update projects." on projects for update using (auth.role() = 'authenticated');

-- Insert default projects if table is empty
insert into projects (name, description, status)
select 'HRMS Software', 'Human Resource Management System Development', 'Active'
where not exists (select 1 from projects where name = 'HRMS Software');

insert into projects (name, description, status)
select 'UHDMS Core', 'Core Unified Healthcare Database Management System', 'Active'
where not exists (select 1 from projects where name = 'UHDMS Core');

insert into projects (name, description, status)
select 'Mobile App', 'Employee Self Service Mobile Application', 'Active'
where not exists (select 1 from projects where name = 'Mobile App');
