-- Create Payroll Runs Table
CREATE TABLE IF NOT EXISTS public.payroll_runs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    month TEXT NOT NULL, -- e.g. "January 2026"
    year INTEGER NOT NULL,
    total_employees INTEGER DEFAULT 0,
    total_payout DECIMAL(12, 2) DEFAULT 0.00,
    status TEXT DEFAULT 'Draft', -- 'Draft', 'Paid'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Payslips Table
CREATE TABLE IF NOT EXISTS public.payslips (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    run_id BIGINT REFERENCES public.payroll_runs(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) NOT NULL,
    basic_salary DECIMAL(10, 2) NOT NULL,
    additions DECIMAL(10, 2) DEFAULT 0.00,
    deductions DECIMAL(10, 2) DEFAULT 0.00,
    net_salary DECIMAL(10, 2) NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.payroll_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payslips ENABLE ROW LEVEL SECURITY;

-- Policies (Simplified for MVP)
CREATE POLICY "Admins can manage payroll runs" ON public.payroll_runs FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins can manage payslips" ON public.payslips FOR ALL TO authenticated USING (true);
-- Individual users functionality to view their OWN payslips can be added later:
-- CREATE POLICY "Users view own payslips" ON public.payslips FOR SELECT TO authenticated USING (auth.uid() = user_id);
