-- Create Activities Table (for Recent Activity Feed)
create table if not exists activities (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null, -- Who performed the action
  action text not null, -- e.g., 'committed', 'completed', 'commented'
  target text, -- e.g., 'Task #123', 'Bug #456', 'uhdms-core'
  meta jsonb default '{}'::jsonb, -- Store extra details like links, specific timestamps, or smaller context
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Activities
alter table activities enable row level security;
create policy "Activities are viewable by everyone." on activities for select using (true);
create policy "Authenticated users can insert activities." on activities for insert with check (auth.role() = 'authenticated');


-- Create Interviews Table (for Upcoming Interviews Widget)
create table if not exists interviews (
  id bigint generated by default as identity primary key,
  candidate_name text not null,
  role text not null, -- e.g., 'Senior Frontend Engineer'
  interviewer_id uuid references auth.users, -- Ideally references profiles, but auth.users is safer foreign key base
  scheduled_at timestamp with time zone not null,
  status text default 'Scheduled', -- Scheduled, Completed, Cancelled
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Interviews
alter table interviews enable row level security;
create policy "Interviews are viewable by everyone." on interviews for select using (true);
create policy "Authenticated users can insert interviews." on interviews for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update interviews." on interviews for update using (auth.role() = 'authenticated');


-- Create Announcements Table (for New Feature/System Announcements)
create table if not exists announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  type text default 'info', -- info, warning, success
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Announcements
alter table announcements enable row level security;
create policy "Announcements are viewable by everyone." on announcements for select using (true);
-- Only allow specific roles (or just authenticated for now) to manage announcements
create policy "Authenticated users can insert announcements." on announcements for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update announcements." on announcements for update using (auth.role() = 'authenticated');


-- Insert specific Dummy Data for Dashboard Visualization (User can remove this later)
-- Use a DO block to insert only if empty to avoid duplicates on re-runs
DO $$
DECLARE
  test_user_id uuid;
BEGIN
  -- Attempt to get a user ID to link foreign keys. If no user exists, skip data insertion or use NULL where allowed.
  -- LIMIT 1 is just to pick *someone* to be the actor for the demo data.
  SELECT id INTO test_user_id FROM auth.users LIMIT 1;

  IF test_user_id IS NOT NULL THEN
      -- DUMMY ACTIVITIES
      IF NOT EXISTS (SELECT 1 FROM activities) THEN
        INSERT INTO activities (user_id, action, target, created_at) VALUES
        (test_user_id, 'committed code', 'uhdms-core', now() - interval '2 hours'),
        (test_user_id, 'completed', 'Task #441-Production', now() - interval '4 hours'),
        (test_user_id, 'reported', 'Critical Bug in Login', now() - interval '6 hours');
      END IF;

      -- DUMMY INTERVIEWS
      IF NOT EXISTS (SELECT 1 FROM interviews) THEN
        INSERT INTO interviews (candidate_name, role, interviewer_id, scheduled_at) VALUES
        ('Marcus Sterling', 'Senior Frontend Engineer', test_user_id, now() + interval '1 day'),
        ('Sarah Jenkins', 'HR Generalist', test_user_id, now() + interval '2 days');
      END IF;
  END IF;

  -- DUMMY ANNOUNCEMENTS (No foreign key needed)
  IF NOT EXISTS (SELECT 1 FROM announcements) THEN
        INSERT INTO announcements (title, content, type) VALUES
        ('New Feature!', 'The Test Suite runner now supports automated UI regression testing with AI analysis.', 'info');
  END IF;
END $$;
