-- Create Teams Table
create table if not exists teams (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  leader_id uuid references auth.users, -- Optional team lead
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on teams
alter table teams enable row level security;
create policy "Teams are viewable by everyone." on teams for select using (true);
create policy "Admins and HR can manage teams." on teams for all using (
  public.get_my_role() IN ('admin', 'hr')
);

-- Create Team Members Table (for assigning roles within a team)
create table if not exists team_members (
  id bigint generated by default as identity primary key,
  team_id bigint references teams on delete cascade not null,
  user_id uuid references auth.users not null,
  role text default 'Member', -- e.g. Lead, Senior, Member
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(team_id, user_id)
);

-- Enable RLS on team_members
alter table team_members enable row level security;
create policy "Team members are viewable by everyone." on team_members for select using (true);
create policy "Admins and HR can manage team members." on team_members for all using (
  public.get_my_role() IN ('admin', 'hr')
);
