
-- Table to store standard checklists for onboarding/offboarding
CREATE TABLE IF NOT EXISTS lifecycle_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    stage TEXT NOT NULL CHECK (stage IN ('onboarding', 'offboarding')),
    department TEXT NOT NULL CHECK (department IN ('HR', 'IT', 'Finance', 'Admin')), -- Who is responsible
    is_mandatory BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table to track progress for specific employees
CREATE TABLE IF NOT EXISTS employee_lifecycle_progress (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    task_id BIGINT REFERENCES lifecycle_tasks(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'skipped')),
    notes TEXT,
    completed_by UUID REFERENCES profiles(id),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(employee_id, task_id)
);

-- Enable RLS
ALTER TABLE lifecycle_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee_lifecycle_progress ENABLE ROW LEVEL SECURITY;

-- Policies for Tasks (Viewable by everyone, Manageable by Admin/HR)
CREATE POLICY "Everyone can view lifecycle tasks" ON lifecycle_tasks FOR SELECT USING (true);
CREATE POLICY "Admins/HR can manage lifecycle tasks" ON lifecycle_tasks USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'hr'))
);

-- Policies for Progress
CREATE POLICY "Admins/HR can view/manage all progress" ON employee_lifecycle_progress USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'hr'))
);

CREATE POLICY "Employees can view own progress" ON employee_lifecycle_progress FOR SELECT USING (auth.uid() = employee_id);

-- Seed some default tasks
INSERT INTO lifecycle_tasks (title, stage, department) VALUES
-- Onboarding
('Create Company Email', 'onboarding', 'IT'),
('Assign Laptop/Workstation', 'onboarding', 'IT'),
('Add to Slack/Teams', 'onboarding', 'IT'),
('Collect Signed Offer Letter', 'onboarding', 'HR'),
('Collect Identity Proofs', 'onboarding', 'HR'),
('Setup Payroll Account', 'onboarding', 'Finance'),
('Issue ID Card', 'onboarding', 'Admin'),

-- Offboarding
('Revoke System Access', 'offboarding', 'IT'),
('Collect Laptop/Assets', 'offboarding', 'IT'),
(' Conduct Exit Interview', 'offboarding', 'HR'),
('Process Full & Final Settlement', 'offboarding', 'Finance'),
('Revoke ID Card', 'offboarding', 'Admin');
