-- Create test_case_comments table
CREATE TABLE IF NOT EXISTS test_case_comments (
    id bigint generated by default as identity primary key,
    case_id uuid references test_cases(id) on delete cascade not null, -- Changed from bigint to uuid
    user_id uuid references auth.users(id),
    content text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE test_case_comments ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable read access for all users" ON test_case_comments FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON test_case_comments FOR INSERT WITH CHECK (auth.role() = 'authenticated');
