-- Create Meetings Table
create table if not exists meetings (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone,
  host_id uuid references auth.users not null,
  meeting_link text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table meetings enable row level security;
create policy "Meetings are viewable by everyone" on meetings for select using (true);
create policy "Authenticated users can create meetings" on meetings for insert with check (auth.role() = 'authenticated');

-- Meeting Participants
create table if not exists meeting_participants (
  id bigint generated by default as identity primary key,
  meeting_id bigint references meetings on delete cascade not null,
  user_id uuid references auth.users not null,
  status text default 'pending', -- pending, accepted, declined
  unique(meeting_id, user_id)
);

alter table meeting_participants enable row level security;
create policy "Participants viewable by everyone" on meeting_participants for select using (true);
create policy "Authenticated users can add participants" on meeting_participants for insert with check (auth.role() = 'authenticated');
