-- Create Events Table for Calendar
create table if not exists events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  all_day boolean default false,
  type text default 'event', -- event, holiday, reminder
  color text, -- e.g. #ff0000
  user_id uuid references auth.users, -- null if system/global event
  is_public boolean default false, -- true for company holidays
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table events enable row level security;

-- Policies
-- 1. Everyone can view public events (Holidays)
create policy "Public events are viewable by everyone" on events for select using (is_public = true);

-- 2. Users can view their own events
create policy "Users can view own events" on events for select using (auth.uid() = user_id);

-- 3. Authenticated users can insert their own events
create policy "Users can insert own events" on events for insert with check (auth.uid() = user_id);

-- 4. Users can update their own events
create policy "Users can update own events" on events for update using (auth.uid() = user_id);

-- 5. Users can delete their own events
create policy "Users can delete own events" on events for delete using (auth.uid() = user_id);
