-- Create Bug Comments Table
-- Drop if exists
DROP TABLE IF EXISTS bug_comments;

create table bug_comments (
  id bigint generated by default as identity primary key,
  bug_id uuid references bugs(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete set null, -- Reference public.profiles
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
alter table bug_comments enable row level security;

-- Policies
create policy "Comments are viewable by everyone." on bug_comments for select using (true);
create policy "Authenticated users can insert comments." on bug_comments for insert with check (auth.role() = 'authenticated');
create policy "Users can update their own comments." on bug_comments for update using (auth.uid() = user_id);
create policy "Users can delete their own comments." on bug_comments for delete using (auth.uid() = user_id);
