-- Create Interviews Table
create table if not exists interviews (
  id bigint generated by default as identity primary key,
  candidate_name text not null,
  role text,
  scheduled_at timestamp with time zone not null,
  interviewer_id uuid references auth.users,
  status text default 'Scheduled', -- Scheduled, Completed, Cancelled
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on interviews
alter table interviews enable row level security;

-- Drop existing policies to allow re-running script (Idempotency)
drop policy if exists "Interviews are viewable by everyone." on interviews;
drop policy if exists "Authenticated users can insert interviews." on interviews;
drop policy if exists "Authenticated users can update interviews." on interviews;

create policy "Interviews are viewable by everyone." on interviews for select using (true);
create policy "Authenticated users can insert interviews." on interviews for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update interviews." on interviews for update using (auth.role() = 'authenticated');

-- Create Activities Table (Audit Log)
create table if not exists activities (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  action text not null, -- e.g., 'created ticket', 'deployed to prod'
  target text, -- e.g., 'T-101', 'v1.2.0'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ensure user_id is nullable (Fix for constraint error if table exists with NOT NULL)
alter table activities alter column user_id drop not null;

-- Enable RLS on activities
alter table activities enable row level security;

drop policy if exists "Activities are viewable by everyone." on activities;
drop policy if exists "Authenticated users can insert activities." on activities;

create policy "Activities are viewable by everyone." on activities for select using (true);
create policy "Authenticated users can insert activities." on activities for insert with check (auth.role() = 'authenticated');

-- Create Announcements Table
create table if not exists announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid references auth.users
);

-- Enable RLS on announcements
alter table announcements enable row level security;

drop policy if exists "Announcements are viewable by everyone." on announcements;
drop policy if exists "Admins/HR can insert announcements." on announcements;
drop policy if exists "Admins/HR can update announcements." on announcements;

create policy "Announcements are viewable by everyone." on announcements for select using (true);
create policy "Admins/HR can insert announcements." on announcements for insert with check (auth.role() in ('admin', 'hr'));
create policy "Admins/HR can update announcements." on announcements for update using (auth.role() in ('admin', 'hr'));

-- Seed Data (Safe Insert)
-- Interviews
insert into interviews (candidate_name, role, scheduled_at, status)
select 'Sarah Johnson', 'Senior Frontend Dev', now() + interval '2 hours', 'Scheduled'
where not exists (select 1 from interviews where candidate_name = 'Sarah Johnson');

insert into interviews (candidate_name, role, scheduled_at, status)
select 'Michael Chen', 'Product Manager', now() + interval '1 day 4 hours', 'Scheduled'
where not exists (select 1 from interviews where candidate_name = 'Michael Chen');

insert into interviews (candidate_name, role, scheduled_at, status)
select 'Jessica Davis', 'QA Engineer', now() + interval '2 days', 'Scheduled'
where not exists (select 1 from interviews where candidate_name = 'Jessica Davis');

-- Activities
-- We use NULL for user_id for system events (allowed now by ALTER statement above)
insert into activities (action, target, user_id)
select 'deployed to prod', 'v2.4.0', null
where not exists (select 1 from activities where target = 'v2.4.0');

insert into activities (action, target, user_id)
select 'completed task', 'FIX-402: Login Issue', null
where not exists (select 1 from activities where target = 'FIX-402: Login Issue');

insert into activities (action, target, user_id)
select 'reported bug', 'BUG-105: Layout Shift', null
where not exists (select 1 from activities where target = 'BUG-105: Layout Shift');

insert into activities (action, target, user_id)
select 'created ticket', 'FE-203: Dashboard Widgets', null
where not exists (select 1 from activities where target = 'FE-203: Dashboard Widgets');

-- Announcements
insert into announcements (title, content, active)
select 'New Feature: Dark Mode', 'We have successfully launched Dark Mode! Toggle it in the sidebar settings to reduce eye strain during late-night coding sessions.', true
where not exists (select 1 from announcements where title = 'New Feature: Dark Mode');
