
-- 1. Fix Bug Comments (Re-point to auth.users to avoid "Profile not found" blocking)
DO $$ BEGIN
    ALTER TABLE bug_comments DROP CONSTRAINT IF EXISTS bug_comments_user_id_fkey;
    ALTER TABLE bug_comments ADD CONSTRAINT bug_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
EXCEPTION
    WHEN undefined_table THEN NULL;
END $$;

-- 2. Fix Bug History (Re-point to auth.users)
DO $$ BEGIN
    ALTER TABLE bug_history DROP CONSTRAINT IF EXISTS bug_history_user_id_fkey;
    ALTER TABLE bug_history ADD CONSTRAINT bug_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
EXCEPTION
    WHEN undefined_table THEN NULL;
END $$;

-- 3. Fix Bug Attachments (Re-point to auth.users)
DO $$ BEGIN
    ALTER TABLE bug_attachments DROP CONSTRAINT IF EXISTS bug_attachments_uploaded_by_fkey;
    ALTER TABLE bug_attachments ADD CONSTRAINT bug_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id) ON DELETE SET NULL;
EXCEPTION
    WHEN undefined_table THEN NULL;
END $$;

-- 4. Enable RLS on Profiles and Allow Insert (Fixes "ensureProfileExists" failure)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert their own profile" 
ON public.profiles FOR INSERT 
WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
CREATE POLICY "Users can update their own profile" 
ON public.profiles FOR UPDATE 
USING (auth.uid() = id);

DROP POLICY IF EXISTS "Profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Profiles are viewable by everyone" 
ON public.profiles FOR SELECT 
USING (true);

-- 5. Ensure Issue Links Table Exists (For "Linked Tasks is not working")
CREATE TABLE IF NOT EXISTS public.issue_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_bug_id UUID REFERENCES public.bugs(id) ON DELETE CASCADE NOT NULL,
    target_bug_id UUID REFERENCES public.bugs(id) ON DELETE CASCADE,
    target_task_id UUID REFERENCES public.tasks(id) ON DELETE CASCADE, -- Assuming UUID
    link_type TEXT DEFAULT 'relates_to',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT one_target_only CHECK (
        (target_bug_id IS NOT NULL AND target_task_id IS NULL) OR 
        (target_bug_id IS NULL AND target_task_id IS NOT NULL)
    )
);

ALTER TABLE public.issue_links ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all for authenticated" ON public.issue_links;
CREATE POLICY "Enable all for authenticated" ON public.issue_links FOR ALL USING (auth.role() = 'authenticated');
