
-- 1. Create the Storage Bucket (Fixes "Bucket not found")
INSERT INTO storage.buckets (id, name, public) 
VALUES ('bug_attachments', 'bug_attachments', true)
ON CONFLICT (id) DO NOTHING;

-- 2. Allow Public Access to the Bucket (Read/Write for authenticated users)
-- Remove existing policies to avoid conflicts
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Upload" ON storage.objects;

CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'bug_attachments' );
CREATE POLICY "Authenticated Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'bug_attachments' AND auth.role() = 'authenticated' );

-- 3. Fix History Logging (Permissive Policy)
-- Ensure the table exists (should already be there, but just in case)
CREATE TABLE IF NOT EXISTS public.bug_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bug_id UUID REFERENCES public.bugs(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, 
    field_changed TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.bug_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable insert for authenticated" ON public.bug_history;
CREATE POLICY "Enable insert for authenticated" 
ON public.bug_history FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable select for authenticated" ON public.bug_history;
CREATE POLICY "Enable select for authenticated" 
ON public.bug_history FOR SELECT 
USING (auth.role() = 'authenticated');
