-- Drop tables to reset schema (since we need to change Foreign Key targets)
drop table if exists team_members;
drop table if exists teams;

-- Create Teams table referencing PROFILES (not auth.users) for easier joins
create table teams (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  leader_id uuid references profiles(id), -- Changed to profiles
  type text default 'Department',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Team Members table referencing PROFILES
create table team_members (
  id bigint generated by default as identity primary key,
  team_id bigint references teams on delete cascade not null,
  user_id uuid references profiles(id) not null, -- Changed to profiles
  role text default 'Member',
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(team_id, user_id)
);

-- Enable RLS
alter table teams enable row level security;
alter table team_members enable row level security;

-- Create Policies
create policy "Teams are viewable by everyone." on teams for select using (true);
create policy "Authenticated users can insert teams." on teams for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update teams." on teams for update using (auth.role() = 'authenticated');

create policy "Team members are viewable by everyone." on team_members for select using (true);
create policy "Authenticated users can insert team members." on team_members for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update team members." on team_members for update using (auth.role() = 'authenticated');
create policy "Authenticated users can delete team members." on team_members for delete using (auth.role() = 'authenticated');
